### ISSUE TITLE
请问空字符在initgrammar（）中该如何表示？

### ISSUE THREAD

**Issue by Xu-pixel** [sleep-jyx/compiler#2]
![image](https://user-images.githubusercontent.com/58813571/172590634-cd570b3f-f596-4cdc-8418-2bacb29db7c0.png)

**Comment by Xu-pixel** [comment]
明白了，是#？

**Comment by sleep-jyx** [comment]
你好，如果“空字符”指的是“空”，那么在程序中用null来表示，比如图中箭头指出来的地方可以写成“R-&gt;null”。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sleep-jyx/compiler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 晚上6:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[sleep-jyx/compiler] 请问空字符在initgrammar（）中该如何表示？ (Issue #2)

**Comment by Xu-pixel** [comment]
好的，感谢
